[package]
name                 = "pacquet-scheduler"
description          = "Resource-aware task scheduling utilities used by pacquet"
version              = "0.0.1"
publish              = false
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

[dependencies]
tokio   = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
